In [1]:
import numpy as np
import pandas as pd

### Lista de Python

Las tablas de datos las podemos ingresar como *listas*. Es la opción más limitada para trabajar con tablas de datos, pero las listas se pueden convertir a otro tipo mejor.

In [30]:
datos = [(1, 10, 100),
        (2, 20, 200),
        (3, 30, 300),
        (4, 40, 400),
        (5, 50, 500)]
print(datos)
type(datos)

[(1, 10, 100), (2, 20, 200), (3, 30, 300), (4, 40, 400), (5, 50, 500)]


list

## Numpy

Numpy es una librería especialmente diseñada para trabajar con matrices. Podemos convertir *listas de Python* en *arrays de Numpy* con la siguiente orden.

In [29]:
d = np.array(datos)
print(d)
type(d)

[[  1  10 100]
 [  2  20 200]
 [  3  30 300]
 [  4  40 400]
 [  5  50 500]]


numpy.ndarray

### Acceso a los elementos de una matriz

Vemos debajo algunos ejemplos que muestran cómo acceder a los elementos de la matriz. 

#### Acceso a una submatriz 

El primer rango de números indica las filas deseadas para la submatriz, el segundo rango de números indica las columnas. El primer número del rango está incluido y el segundo no. Por ejemplo, si queremos seleccionar la fila 2 y 3, tenemos que usar el rango 2:4.

In [43]:
d[2:4, 0:2]

array([[ 3, 30],
       [ 4, 40]])

In [24]:
d[0,0]

1

#### Acceso a una columna o fila, completa o parcial

Si queremos usar una fila o columna completa, colocamos los dos puntos aisladamente, sin números antes y después. 

In [44]:
d[:, 1]

array([10, 20, 30, 40, 50])

In [45]:
d[2, :]

array([  3,  30, 300])

A continuación se elije una sección de la columna 1.

In [46]:
d[2:4, 1]

array([30, 40])

## Pandas

Lectura de un archivo con datos separados por comas (extensión csv). Si no se coloca *header=None* se utiliza la primera fila de datos del archivo como nombre para las columnas.

In [74]:
tablita = pd.read_csv("tabla.csv", header=None)

In [75]:
tablita

0   1    2
0  1  10  100
1  2  20  200
2  3  30  300

Para nombrar las columnas al cargar el archivo csv, se puede utilizar una lista de nombres.

In [89]:
header_list = ["Uno", "Dos", "Tres"]
tabla = pd.read_csv("tabla.csv", names=header_list)
tabla

Uno  Dos  Tres
0    1   10   100
1    2   20   200
2    3   30   300

Para acceder a una columna, se utiliza su nombre.

In [90]:
tabla["Tres"]

0    100
1    200
2    300
Name: Tres, dtype: int64

In [91]:
tablita[2]

0    100
1    200
2    300
Name: 2, dtype: int64

Para acceder a un elemento de la columna, se utiliza su índice.

In [92]:
tabla["Tres"][1]

200

In [93]:
tablita[2][1]

200

### Conversión de DataFrame a NumpyArray

In [102]:
nuevaTabla = tabla.to_numpy()
print(nuevaTabla)
type(nuevaTabla)

[[  1  10 100]
 [  2  20 200]
 [  3  30 300]]


numpy.ndarray

### Conversión de NumpyArray a DataFrame

In [105]:
nuevoArray = pd.DataFrame(data=nuevaTabla)
nuevoArray

0   1    2
0  1  10  100
1  2  20  200
2  3  30  300

In [106]:
type(nuevoArray)

pandas.core.frame.DataFrame